version: '3.8'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: mironion/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db

  frontend:
    image: mironion/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static/

  gateway:
    image: mironion/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/mediafiles/
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend